### ISSUE TITLE
notifications are sometimes very large

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssb-notifier#3]
it appears that notificiations are displayed according to the image size (at least on my window manager - awesome) some avatars are very large and the notification takes up half the screen! is there a way to size these consistently?

**Comment by clehner** [comment]
They could be resized on-the-fly maybe. What notification daemon are you using? (that is usually separate from the WM)

**Comment by dominictarr** [comment]
how do I find out? it just works I never configured anything apart from `apt-get` installing awesome

**Comment by clehner** [comment]
the proper way would be to query dbus but i'm not sure how to do that. try triggering a notification (i.e. `notify-send foo`), then run `xprop` in a terminal, click the notification, and see what the console output shows (e.g. what is the resulting `WM_NAME` and `WM_CLASS`)
