### ISSUE TITLE
sometimes shows default avatar, when uxer has a valid avatar

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssb-notifier#4]
I'm seeing notifications that show the boxy thing, when that user actually has an avatar image set.
I'm guessing it may be because the avatar file type is a thing that the browser can display but notifier can't?

**Comment by clehner** [comment]
Does this happen consistently with certain users?
It could be a problem with the way profile pics are looked up - https://github.com/ssbc/ssb-notifier/blob/master/notifications.js#L93
