### ISSUE TITLE
use multiblob#resolve instead of copying the blob

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssb-notifier#5]
hey, looking into refactoring out your avatar lookup code.
if you need to access an avartar image directly,
you can use https://github.com/dominictarr/multiblob/blob/master/index.js#L262-L264
to a handle on the file inside the blob store, as I acknowledge sometimes this is necessary
(Just don't mutate it!!!)

**Comment by clehner** [comment]
thanks, that looks useful. what about a case where the ssb-client is on a different machine than the sbot? i suppose we don't have that case currently but would we want it in the future?
